services:
  dockmon:
    build:
      context: .
    ports:
      - "3005:3000" # Benutzerpräferenz: Port 3005 für externen Zugriff
    environment:
      - USERNAME=Admin
      - PASSWORD=PASSWORD
      - SESSION_SECRET=Secret
    volumes:
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["node", "index.js"]