services:
  dockmon:
    build:
      context: .
    ports:
      - "3005:3000" 
    environment:
      - USERNAME=${USERNAME}
      - PASSWORD=${PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    volumes:
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["node", "index.js"]